import type { SupabaseClient } from "@supabase/supabase-js";
type Db = SupabaseClient<any, any, any>;
async function db(): Promise<Db> { const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); return supabaseAdmin as unknown as Db; }
async function requireAdmin() { const { requireAdmin } = await import("./admin-session.server"); await requireAdmin(); }
async function enrichPosts(database: Db, rows: any[], userId?: string) {
  const [{ data: drivers }, { data: teams }] = await Promise.all([database.from("drivers").select("slug, name, flag, color_key"), database.from("teams").select("slug, name, flag, color_key, logo_url")]);
  const driverBy = new Map((drivers ?? []).map((x: any) => [x.slug, x])); const teamBy = new Map((teams ?? []).map((x: any) => [x.slug, x]));
  const ids = rows.map(r => r.id);
  const likes = ids.length ? await database.from("official_entity_post_likes").select("post_id, user_id").in("post_id", ids) : { data: [] };
  const comments = ids.length ? await database.from("comments").select("entity_id").eq("entity_type", "official_post").in("entity_id", ids) : { data: [] };
  const likeCount = new Map<string, number>(); const mine = new Set<string>();
  for (const l of likes.data ?? []) { likeCount.set(l.post_id, (likeCount.get(l.post_id) ?? 0) + 1); if (userId && l.user_id === userId) mine.add(l.post_id); }
  const commentCount = new Map<string, number>(); for (const c of comments.data ?? []) commentCount.set(c.entity_id, (commentCount.get(c.entity_id) ?? 0) + 1);
  return rows.map(p => { const e: any = p.entity_type === "driver" ? driverBy.get(p.entity_slug) : teamBy.get(p.entity_slug); return { ...p, name: e?.name ?? p.entity_slug, flag: e?.flag ?? "", color_key: e?.color_key ?? "red", logo_url: e?.logo_url ?? null, like_count: likeCount.get(p.id) ?? 0, liked_by_me: mine.has(p.id), comment_count: commentCount.get(p.id) ?? 0, verified_official: true }; });
}
export async function adminCreateOfficialPost(input: { entity_type: "driver" | "team"; entity_slug: string; body: string; media_url?: string | null }) {
  await requireAdmin(); const database = await db(); const table = input.entity_type === "driver" ? "drivers" : "teams";
  const { data: entity } = await database.from(table).select("slug, name").eq("slug", input.entity_slug).maybeSingle(); if (!entity) throw new Error("Kuljettajaa tai tiimiä ei löytynyt");
  const { data: post, error } = await database.from("official_entity_posts").insert({ entity_type: input.entity_type, entity_slug: input.entity_slug, body: input.body.trim(), media_url: input.media_url ?? null, verified_official: true, published: true }).select().single(); if (error) throw error;
  const { data: followers } = await database.from("follows").select("user_id").eq("entity_type", input.entity_type).eq("entity_slug", input.entity_slug);
  if ((followers ?? []).length) await database.from("notifications").insert((followers ?? []).map((f: any) => ({ user_id: f.user_id, type: "official_post", title: `${entity.name} julkaisi uuden postauksen ✓`, body: "Avaa Seuratut → Julkaisut nähdäksesi julkaisun.", club_id: null, link: "/seuratut?tab=posts" })));
  return post;
}
export async function listOfficialPosts(userId?: string) { const database = await db(); const { data, error } = await database.from("official_entity_posts").select("id, entity_type, entity_slug, body, media_url, created_at, verified_official").eq("published", true).eq("verified_official", true).order("created_at", { ascending: false }).limit(100); if (error) throw error; return enrichPosts(database, data ?? [], userId); }
export async function listEntityOfficialPosts(entity_type: "driver" | "team", entity_slug: string) { const database = await db(); const { data, error } = await database.from("official_entity_posts").select("id, entity_type, entity_slug, body, media_url, created_at, verified_official").eq("published", true).eq("verified_official", true).eq("entity_type", entity_type).eq("entity_slug", entity_slug).order("created_at", { ascending: false }).limit(50); if (error) throw error; return enrichPosts(database, data ?? []); }
export async function toggleOfficialPostLike(userId: string, postId: string) { const database = await db(); const { data: existing } = await database.from("official_entity_post_likes").select("post_id").eq("post_id", postId).eq("user_id", userId).maybeSingle(); if (existing) await database.from("official_entity_post_likes").delete().eq("post_id", postId).eq("user_id", userId); else await database.from("official_entity_post_likes").insert({ post_id: postId, user_id: userId }); const { count } = await database.from("official_entity_post_likes").select("post_id", { count: "exact", head: true }).eq("post_id", postId); return { liked: !existing, like_count: count ?? 0 }; }
export async function officialPostComments(postId: string) { const database = await db(); const { data, error } = await database.from("comments").select("id, user_id, body, created_at").eq("entity_type", "official_post").eq("entity_id", postId).order("created_at", { ascending: true }); if (error) throw error; const ids = [...new Set((data ?? []).map((x: any) => x.user_id))]; const { data: profiles } = ids.length ? await database.from("profiles").select("id, display_name, avatar_url").in("id", ids) : { data: [] }; const by = new Map((profiles ?? []).map((x: any) => [x.id, x])); return (data ?? []).map((x: any) => ({ ...x, display_name: by.get(x.user_id)?.display_name ?? "Vierailija", avatar_url: by.get(x.user_id)?.avatar_url ?? null })); }
export async function commentOfficialPost(userId: string, postId: string, body: string) { const database = await db(); const { data, error } = await database.from("comments").insert({ entity_type: "official_post", entity_id: postId, user_id: userId, body: body.trim() }).select().single(); if (error) throw error; return data; }
