import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { adminCreateOfficialPost } from "@/lib/official-posts.functions";
import { createMediaUploadUrl, finalizeMediaUpload } from "@/lib/upload.functions";
import { getAdminStatus } from "@/lib/admin.functions";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export const Route = createFileRoute("/admin-julkaisut")({ head: () => ({ meta: [{ title: "Admin — Julkaisut — RyhäMonoposto" }] }), component: AdminPosts });

function AdminPosts() {
  const status = useServerFn(getAdminStatus), create = useServerFn(adminCreateOfficialPost), sign = useServerFn(createMediaUploadUrl), finalize = useServerFn(finalizeMediaUpload), qc = useQueryClient();
  const [isAdmin, setIsAdmin] = useState(false), [kind, setKind] = useState<"driver"|"team">("driver"), [slug, setSlug] = useState(""), [body, setBody] = useState(""), [media, setMedia] = useState<string|null>(null), [busy, setBusy] = useState(false);
  const drivers = useQuery({ queryKey:["admin-post-drivers"], queryFn:async()=> (await supabase.from("drivers").select("slug,name,flag").order("name")).data ?? [] });
  const teams = useQuery({ queryKey:["admin-post-teams"], queryFn:async()=> (await supabase.from("teams").select("slug,name,flag").order("name")).data ?? [] });
  const entities:any[] = kind === "driver" ? drivers.data ?? [] : teams.data ?? [];
  const selected = useMemo(()=>entities.find(e=>e.slug===slug),[entities,slug]);
  useEffect(()=>{ status().then(r=>setIsAdmin(r.admin)); },[]); useEffect(()=>setSlug(""),[kind]);
  async function chooseFile(file?:File){ if(!file)return; if(!/^(image|video)\//.test(file.type))return toast.error("Vain kuva- tai videotiedosto"); if(file.size>15*1024*1024)return toast.error("Tiedosto voi olla enintään 15 Mt"); setBusy(true); try{ const s=await sign({data:{filename:file.name,contentType:file.type}}); const {error}=await supabase.storage.from("media").uploadToSignedUrl(s.key,s.token,file); if(error)throw error; setMedia((await finalize({data:{key:s.key}})).url); toast.success("Media ladattu"); }catch(e:any){toast.error(e?.message??"Median lataus epäonnistui")}finally{setBusy(false)} }
  async function submit(e:React.FormEvent){e.preventDefault(); if(!slug||(!body.trim()&&!media))return toast.error("Valitse kohde ja lisää teksti tai media"); setBusy(true); try{await create({data:{entity_type:kind,entity_slug:slug,body,media_url:media}}); toast.success(`${selected?.name??"Kohde"} julkaisi postauksen ✓`); setBody("");setMedia(null);qc.invalidateQueries({queryKey:["official-posts"]});}catch(err:any){toast.error(err?.message??"Julkaisu epäonnistui")}finally{setBusy(false)}}
  if(!isAdmin)return <main className="mx-auto max-w-3xl px-4 py-10"><div className="card-dark p-6"><h1 className="font-display uppercase tracking-widest text-primary">Admin-julkaisut</h1><p className="text-sm text-muted-foreground mt-3">Kirjaudu ensin admin-tilaan Asetuksista.</p></div></main>;
  return <main className="mx-auto max-w-3xl px-4 py-8 space-y-5"><header><h1 className="font-display uppercase tracking-widest text-2xl text-primary">Admin-julkaisu</h1><p className="text-sm text-muted-foreground mt-2">Julkaise kuljettajan tai tiimin virallisella nimellä. Julkaisu saa automaattisesti ✓-vahvistuksen.</p><div className="hairline-red mt-3"/></header><form onSubmit={submit} className="card-dark p-5 space-y-4"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setKind("driver")} className={`p-2 rounded border ${kind==="driver"?"border-primary bg-primary/15 text-primary":"border-primary/20"}`}>🏎️ Kuljettaja</button><button type="button" onClick={()=>setKind("team")} className={`p-2 rounded border ${kind==="team"?"border-primary bg-primary/15 text-primary":"border-primary/20"}`}>👥 Tiimi</button></div><select value={slug} onChange={e=>setSlug(e.target.value)} className="w-full bg-black border border-primary/30 rounded p-3 text-sm"><option value="">Valitse {kind==="driver"?"kuljettaja":"tiimi"}</option>{entities.map(e=><option key={e.slug} value={e.slug}>{e.flag} {e.name}</option>)}</select><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Kirjoita julkaisu…" rows={7} className="w-full bg-black border border-primary/30 rounded p-3 text-sm"/><div className="flex items-center gap-3"><label className="rounded border border-primary/40 px-3 py-2 text-xs font-display uppercase tracking-widest cursor-pointer">📎 Lisää media<input type="file" accept="image/*,video/*" className="hidden" onChange={e=>chooseFile(e.target.files?.[0])}/></label>{media&&<span className="text-xs text-primary">✓ Media liitetty</span>}</div><button disabled={busy||!slug||(!body.trim()&&!media)} className="w-full rounded bg-primary text-primary-foreground py-3 font-display uppercase tracking-widest disabled:opacity-50">{busy?"Julkaistaan…":`Julkaise ${selected?.name??"kohteen"} nimellä`}</button></form></main>;
}
