import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { getRace, upsertRace, listDrivers } from "@/lib/content.functions";
import { updateSprint } from "@/lib/sprint.functions";
import { generateResultList } from "@/lib/ai-results.functions";
import { useEntityIndex } from "@/components/useEntityIndex";
import { SmartText } from "@/components/SmartText";
import { Comments } from "@/components/Comments";
import { MediaUpload } from "@/components/MediaUpload";
import { EditableText } from "@/components/EditableText";
import { RaceHighlights } from "@/components/RaceHighlights";
import { useAdmin } from "@/components/admin-store";
import { useState } from "react";
import { toast } from "sonner";

export const Route = createFileRoute("/kilpailut/$slug")({ head: ({ params }) => ({ meta: [{ title: `${params.slug} — Kilpailu` }] }), component: RaceDetail });
function youtubeEmbedUrl(url: string | null | undefined): string | null { if (!url) return null; try { const u = new URL(url); let id = ""; if (u.hostname.includes("youtu.be")) id = u.pathname.slice(1); else if (u.searchParams.get("v")) id = u.searchParams.get("v") ?? ""; else if (u.pathname.startsWith("/embed/")) id = u.pathname.split("/embed/")[1] ?? ""; else if (u.pathname.startsWith("/shorts/")) id = u.pathname.split("/shorts/")[1] ?? ""; return id ? `https://www.youtube.com/embed/${id.split(/[?&]/)[0]}` : null; } catch { return null; } }
function YouTubePreview({ url }: { url: string | null | undefined }) { const embed = youtubeEmbedUrl(url); if (!embed) return null; return <div className="mt-2 aspect-video w-full rounded overflow-hidden border border-primary/30 bg-black"><iframe src={embed} title="YouTube-esikatselu" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen className="w-full h-full" /></div>; }

type Session = "sprintQualifying" | "sprint" | "qualifying" | "race";
type SprintRace = { is_sprint_weekend?: boolean | null; sprint_qualifying_content?: string | null; sprint_content?: string | null; sprint_qualifying_media_url?: string | null; sprint_media_url?: string | null; sprint_qualifying_youtube_url?: string | null; sprint_youtube_url?: string | null; sprint_fastest_lap_driver_slug?: string | null };

function RaceDetail() {
  const { slug } = Route.useParams(); const get = useServerFn(getRace); const save = useServerFn(upsertRace); const saveSprint = useServerFn(updateSprint); const list = useServerFn(listDrivers); const genResults = useServerFn(generateResultList); const qc = useQueryClient(); const admin = useAdmin(); const entities = useEntityIndex();
  const driversQuery = useQuery({ queryKey: ["drivers"], queryFn: () => list() }); const q = useQuery({ queryKey: ["race", slug], queryFn: () => get({ data: { slug } }) });
  const [tab, setTab] = useState<Session>("race"); const [aiBusy, setAiBusy] = useState(false);
  if (q.isLoading) return <div className="mx-auto max-w-4xl px-4 py-8">Ladataan…</div>;
  const r = q.data; if (!r) return <div className="mx-auto max-w-4xl px-4 py-8">Kilpailua ei löydy.</div>;
  const isWinterTest = r.round_number === 0; const sprint = r as typeof r & SprintRace; const isSprint = !!sprint.is_sprint_weekend && !isWinterTest; const effectiveTab: Session = isWinterTest ? "race" : tab;
  const special = r as typeof r & { driver_of_the_day_slug?: string | null; fastest_lap_driver_slug?: string | null };
  async function patch(partial: Partial<{ qualifying_content: string; race_content: string; qualifying_media_url: string | null; race_media_url: string | null; youtube_url: string | null; qualifying_youtube_url: string | null; race_youtube_url: string | null; round_number: number | null; driver_of_the_day_slug: string | null; fastest_lap_driver_slug: string | null }>) {
    await save({ data: { id: r.id, name: r.name, flag: r.flag, race_date: r.race_date, round_number: partial.round_number !== undefined ? partial.round_number : (r.round_number ?? null), qualifying_content: partial.qualifying_content ?? r.qualifying_content ?? "", race_content: partial.race_content ?? r.race_content ?? "", qualifying_media_url: partial.qualifying_media_url ?? r.qualifying_media_url ?? null, race_media_url: partial.race_media_url ?? r.race_media_url ?? null, youtube_url: partial.youtube_url ?? r.youtube_url ?? null, qualifying_youtube_url: partial.qualifying_youtube_url ?? r.qualifying_youtube_url ?? null, race_youtube_url: partial.race_youtube_url ?? r.race_youtube_url ?? null, driver_of_the_day_slug: partial.driver_of_the_day_slug !== undefined ? partial.driver_of_the_day_slug : (special.driver_of_the_day_slug ?? null), fastest_lap_driver_slug: partial.fastest_lap_driver_slug !== undefined ? partial.fastest_lap_driver_slug : (special.fastest_lap_driver_slug ?? null) } as any });
    await qc.invalidateQueries({ queryKey: ["race", slug] }); await qc.invalidateQueries({ queryKey: ["standings"] }); toast.success("Tallennettu");
  }
  async function patchSprint(partial: Partial<SprintRace>) { await saveSprint({ data: { id: r.id, ...partial } }); await qc.invalidateQueries({ queryKey: ["race", slug] }); await qc.invalidateQueries({ queryKey: ["standings"] }); toast.success("Sprinttitiedot tallennettu"); }
  async function toggleSprint() { try { await patchSprint({ is_sprint_weekend: !sprint.is_sprint_weekend }); } catch (e: any) { toast.error(e?.message ?? "Sprinttiviikonlopun muuttaminen epäonnistui"); } }

  const activeContent = effectiveTab === "sprintQualifying" ? (sprint.sprint_qualifying_content ?? "") : effectiveTab === "sprint" ? (sprint.sprint_content ?? "") : effectiveTab === "qualifying" ? (r.qualifying_content ?? "") : (r.race_content ?? "");
  const activeMedia = effectiveTab === "sprintQualifying" ? sprint.sprint_qualifying_media_url : effectiveTab === "sprint" ? sprint.sprint_media_url : effectiveTab === "qualifying" ? r.qualifying_media_url : r.race_media_url;
  const activeYoutube = effectiveTab === "sprintQualifying" ? sprint.sprint_qualifying_youtube_url : effectiveTab === "sprint" ? sprint.sprint_youtube_url : effectiveTab === "qualifying" ? (r.qualifying_youtube_url ?? r.youtube_url) : (r.race_youtube_url ?? r.youtube_url);
  const drivers = driversQuery.data ?? [];
  const sessionLabel = effectiveTab === "sprintQualifying" ? "sprintin aika-ajot" : effectiveTab === "sprint" ? "sprintti" : effectiveTab === "qualifying" ? "aika-ajot" : "kisa";
  const isSprintSession = effectiveTab === "sprintQualifying" || effectiveTab === "sprint";
  const tabs: Session[] = isSprint ? ["sprintQualifying", "sprint", "qualifying", "race"] : ["qualifying", "race"];

  return <div className="mx-auto max-w-4xl px-4 py-8">
    <div className="flex items-center gap-3 flex-wrap"><span className="text-3xl">{r.flag}</span>{r.round_number != null && <span className="font-display text-sm px-2 py-1 rounded border border-primary/60 text-primary">{isWinterTest ? "TALVITESTIT" : `R${r.round_number}`}</span>}<h1 className="font-display uppercase tracking-widest text-2xl md:text-3xl">{r.name}</h1>{isSprint && <img src="/images/sprint/ChatGPT Image 16.9.2026 klo 09.46.02.png" alt="Sprinttiviikonloppu" className="h-10 w-auto max-w-20 object-contain" />}</div>
    <div className="hairline-red mt-3 mb-6" />
    <RaceHighlights raceSlug={slug} />
    {!isWinterTest && <div className="flex gap-2 mb-4 overflow-x-auto pb-1">{tabs.map(k => <button key={k} onClick={() => setTab(k)} className={`px-4 py-2 text-xs font-display uppercase tracking-widest rounded border whitespace-nowrap ${tab === k ? "bg-primary text-primary-foreground border-primary" : "border-primary/40 hover:border-primary"}`}>{k === "sprintQualifying" ? "Sprintin aika-ajo" : k === "sprint" ? "Sprintti" : k === "qualifying" ? "Aika-ajo" : "Kisa"}</button>)}</div>}
    {activeMedia && <img src={activeMedia} alt="" className="w-full rounded border border-primary/30 mb-4" />}
    {activeYoutube && <YouTubePreview url={activeYoutube} />}
    {admin.isAdmin && <div className="card-dark p-3 mb-4 space-y-3">
      {isWinterTest && <p className="text-xs text-muted-foreground italic">Talvitestit — vain tulosliuska, ei virallista dataa tilastoihin.</p>}
      <div className="flex items-center gap-2"><span className="text-xs uppercase tracking-widest text-muted-foreground">{sessionLabel} — YouTube-linkki</span><input key={`${effectiveTab}-youtube-${activeYoutube ?? ""}`} defaultValue={activeYoutube ?? ""} onBlur={e => { const v = e.target.value.trim() || null; if (isSprintSession) void patchSprint(effectiveTab === "sprintQualifying" ? { sprint_qualifying_youtube_url: v } : { sprint_youtube_url: v }); else void patch(effectiveTab === "qualifying" ? { qualifying_youtube_url: v } : { race_youtube_url: v }); }} placeholder="https://youtu.be/…" className="flex-1 bg-black/70 border border-primary/30 rounded p-2 text-sm" /></div>
      <div className="flex items-center gap-2"><span className="text-xs uppercase tracking-widest text-muted-foreground">Kilpailun järjestysnumero</span><input key={`round-${r.round_number ?? ""}`} type="number" min={0} max={50} defaultValue={r.round_number ?? ""} onBlur={e => { const raw = e.target.value.trim(); const v = raw ? Math.min(50, Math.max(0, Number(raw))) : null; if (v !== (r.round_number ?? null)) void patch({ round_number: v }); }} className="w-24 bg-black/70 border border-primary/30 rounded p-2 text-sm" /></div>
      <div className="border-t border-primary/20 pt-3 flex flex-col sm:flex-row sm:items-center gap-2"><span className="text-xs uppercase tracking-widest text-muted-foreground flex-1">Sprinttiviikonloppu</span><button type="button" onClick={() => void toggleSprint()} className={`text-xs font-display uppercase tracking-widest border rounded px-3 py-2 self-start ${sprint.is_sprint_weekend ? "border-primary bg-primary/15 text-primary" : "border-primary/40 hover:border-primary"}`}>{sprint.is_sprint_weekend ? "Sprinttiviikonloppu ✓" : "Tee sprinttiviikonlopuksi"}</button></div>
      {!isWinterTest && !isSprintSession && <div className="grid grid-cols-1 md:grid-cols-2 gap-3 border-t border-primary/20 pt-3"><label className="space-y-1"><span className="text-xs uppercase tracking-widest text-muted-foreground">Päivän kuljettaja</span><select value={special.driver_of_the_day_slug ?? ""} onChange={e => void patch({ driver_of_the_day_slug: e.target.value || null })} className="w-full bg-black/70 border border-primary/30 rounded p-2 text-sm"><option value="">Ei valittu</option>{drivers.map(d => <option key={d.slug} value={d.slug}>{d.flag} {d.name}</option>)}</select></label><label className="space-y-1"><span className="text-xs uppercase tracking-widest text-muted-foreground">Nopein kierros</span><select value={special.fastest_lap_driver_slug ?? ""} onChange={e => void patch({ fastest_lap_driver_slug: e.target.value || null })} className="w-full bg-black/70 border border-primary/30 rounded p-2 text-sm"><option value="">Ei valittu</option>{drivers.map(d => <option key={d.slug} value={d.slug}>{d.flag} {d.name}</option>)}</select></label></div>}
      {effectiveTab === "sprint" && <div className="border-t border-primary/20 pt-3"><label className="space-y-1 block"><span className="text-xs uppercase tracking-widest text-muted-foreground">Sprintin nopein kierros</span><select value={sprint.sprint_fastest_lap_driver_slug ?? ""} onChange={e => void patchSprint({ sprint_fastest_lap_driver_slug: e.target.value || null })} className="w-full bg-black/70 border border-primary/30 rounded p-2 text-sm"><option value="">Ei valittu</option>{drivers.map(d => <option key={d.slug} value={d.slug}>{d.flag} {d.name}</option>)}</select></label></div>}
      <MediaUpload label={isWinterTest ? "Testikuva" : `${sessionLabel} -kuva`} currentUrl={activeMedia} onUploaded={async url => { if (isSprintSession) { await patchSprint(effectiveTab === "sprintQualifying" ? { sprint_qualifying_media_url: url } : { sprint_media_url: url }); } else { await patch(effectiveTab === "qualifying" ? { qualifying_media_url: url } : { race_media_url: url }); } setAiBusy(true); try { const yearMatch = r.name.match(/(20\d\d)/); const res = await genResults({ data: { image_url: url, session_label: `${r.name} ${sessionLabel}`, year: yearMatch ? Number(yearMatch[1]) : null } }); if (res.text.trim()) { if (isSprintSession) await patchSprint(effectiveTab === "sprintQualifying" ? { sprint_qualifying_content: res.text } : { sprint_content: res.text }); else await patch(effectiveTab === "qualifying" ? { qualifying_content: res.text } : { race_content: res.text }); toast.success("Tekoäly loi tuloslistan — voit muokata sitä"); } } catch (e: any) { toast.error(`Tuloslistan luonti epäonnistui: ${e?.message ?? ""}`); } finally { setAiBusy(false); } }} />
      {aiBusy && <p className="text-xs text-muted-foreground">Tekoäly lukee tuloskuvaa…</p>}
      <EditableText value={activeContent} multiline placeholder={isSprintSession ? "Kirjoita sprintin tulostiedot… nimet linkittyvät automaattisesti." : isWinterTest ? "Kirjoita talvitestien tulosliuska… nimet linkittyvät automaattisesti." : "Kirjoita tulostiedot… nimet linkittyvät automaattisesti."} onSave={v => isSprintSession ? patchSprint(effectiveTab === "sprintQualifying" ? { sprint_qualifying_content: v } : { sprint_content: v }) : patch(effectiveTab === "qualifying" ? { qualifying_content: v } : { race_content: v })} />
    </div>}
    <SmartText text={activeContent} entities={entities} className="text-sm leading-6" />
    {!isWinterTest && (special.driver_of_the_day_slug || special.fastest_lap_driver_slug || sprint.sprint_fastest_lap_driver_slug) && <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-2">{special.driver_of_the_day_slug && <div className="card-dark p-3"><div className="text-[10px] uppercase tracking-widest text-muted-foreground">Päivän kuljettaja</div><div className="font-display text-primary mt-1">{drivers.find(d => d.slug === special.driver_of_the_day_slug)?.name ?? "–"}</div></div>}{special.fastest_lap_driver_slug && <div className="card-dark p-3"><div className="text-[10px] uppercase tracking-widest text-muted-foreground">Nopein kierros</div><div className="font-display text-primary mt-1">{drivers.find(d => d.slug === special.fastest_lap_driver_slug)?.name ?? "–"}</div></div>}{sprint.sprint_fastest_lap_driver_slug && <div className="card-dark p-3"><div className="text-[10px] uppercase tracking-widest text-muted-foreground">Sprintin nopein kierros</div><div className="font-display text-primary mt-1">{drivers.find(d => d.slug === sprint.sprint_fastest_lap_driver_slug)?.name ?? "–"}</div></div>}</div>}
    <Comments entityType={`race:${effectiveTab}`} entityId={r.id} />
  </div>;
}
