import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { listOfficialPosts } from "@/lib/official-posts.functions";
import { getAdminStatus } from "@/lib/admin.functions";
import { supabase } from "@/integrations/supabase/client";
import { OfficialPostCard } from "@/components/OfficialPostCard";
export const Route=createFileRoute("/postaukset")({head:()=>({meta:[{title:"Postaukset — RyhäMonoposto"}]}),component:PostsPage});
function PostsPage(){const list=useServerFn(listOfficialPosts);const adminStatus=useServerFn(getAdminStatus);const posts=useQuery({queryKey:["official-posts"],queryFn:()=>list(),refetchInterval:30000});const admin=useQuery({queryKey:["admin-status"],queryFn:()=>adminStatus()});const entities=useQuery({queryKey:["official-post-entities"],queryFn:async()=>{const[{data:d},{data:t}]=await Promise.all([supabase.from("drivers").select("slug,name"),supabase.from("teams").select("slug,name")]);return [...(d??[]).map(x=>({...x,type:"driver" as const})),...(t??[]).map(x=>({...x,type:"team" as const}))]}});return <main className="mx-auto max-w-3xl px-4 py-8 space-y-5"><header><h1 className="font-display uppercase tracking-widest text-2xl text-primary">Postaukset</h1><p className="text-sm text-muted-foreground mt-2">Viralliset julkaisut ja yhteisön postaukset. <Link to="/omat-postaukset" className="text-primary hover:underline">+ Luo oma postaus</Link></p><div className="hairline-red mt-3"/></header>{posts.isLoading?<p className="text-sm text-muted-foreground">Ladataan julkaisuja…</p>:!(posts.data??[]).length?<div className="card-dark p-6 text-sm text-muted-foreground">Ei vielä virallisia julkaisuja.</div>:<div className="space-y-3">{(posts.data??[]).map((p:any)=><OfficialPostCard key={p.id} post={p} entities={(entities.data??[]) as any} canAdminDelete={!!admin.data?.admin}/>)}</div>}</main>}
