import { Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { toggleOfficialPostLike, officialPostComments, commentOfficialPost } from "@/lib/official-posts.functions";

type Post={id:string;entity_type:"driver"|"team";entity_slug:string;name:string;flag:string;body:string;media_url?:string|null;created_at:string;like_count:number;liked_by_me?:boolean;comment_count:number;color_key:string}; type Entity={slug:string;name:string;type:"driver"|"team"};
function LinkedBody({body,entities}:{body:string;entities:Entity[]}){const sorted=[...entities].sort((a,b)=>b.name.length-a.name.length);if(!sorted.length)return <span>{body}</span>;const re=new RegExp(`(${sorted.map(e=>e.name.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")).join("|")})`,"gi");return <>{body.split(re).map((part,i)=>{const e=sorted.find(x=>x.name.toLowerCase()===part.toLowerCase());return e?<Link key={i} to={e.type==="driver"?"/kuljettajat/$slug":"/tiimit/$slug"} params={{slug:e.slug}} className="text-primary hover:underline font-display">{part}</Link>:<span key={i}>{part}</span>})}</>}
export function OfficialPostCard({post,entities}:{post:Post;entities:Entity[]}){const like=useServerFn(toggleOfficialPostLike),commentsFn=useServerFn(officialPostComments),comment=useServerFn(commentOfficialPost),qc=useQueryClient();const[open,setOpen]=useState(false),[text,setText]=useState("");const comments=useQuery({queryKey:["official-post-comments",post.id],queryFn:()=>commentsFn({data:{post_id:post.id}}),enabled:open});async function doLike(){try{await like({data:{post_id:post.id}});qc.invalidateQueries({queryKey:["official-posts"]})}catch{}}async function sendComment(e:React.FormEvent){e.preventDefault();if(!text.trim())return;await comment({data:{post_id:post.id,body:text}});setText("");qc.invalidateQueries({queryKey:["official-post-comments",post.id]});qc.invalidateQueries({queryKey:["official-posts"]})}return <article className="card-dark p-4 border-l-2" style={{borderLeftColor:"hsl(var(--primary))"}}><div className="flex items-center gap-2"><Link to={post.entity_type==="driver"?"/kuljettajat/$slug":"/tiimit/$slug"} params={{slug:post.entity_slug}} className="font-display text-sm hover:text-primary">{post.flag} {post.name} <span className="text-primary" title="Vahvistettu">✓</span></Link><span className="text-[10px] text-muted-foreground">• virallinen</span><span className="ml-auto text-[10px] text-muted-foreground">{new Date(post.created_at).toLocaleString("fi-FI")}</span></div><p className="text-sm leading-6 mt-3 whitespace-pre-wrap"><LinkedBody body={post.body} entities={entities}/></p>{post.media_url&&<img src={post.media_url} alt="" className="mt-3 max-h-[560px] w-full object-contain rounded border border-primary/20"/>}<div className="mt-3 flex gap-2 text-xs"><button onClick={doLike} className="border border-primary/20 rounded px-3 py-1">♥ {post.like_count}</button><button onClick={()=>setOpen(v=>!v)} className="border border-primary/20 rounded px-3 py-1">💬 {post.comment_count}</button></div>{open&&<div className="mt-4 border-t border-primary/10 pt-3 space-y-2">{(comments.data??[]).map((c:any)=><div key={c.id} className="text-xs"><b>{c.display_name}</b><span className="text-muted-foreground ml-2">{new Date(c.created_at).toLocaleString("fi-FI")}</span><div className="text-sm mt-1">{c.body}</div></div>)}<form onSubmit={sendComment} className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Kirjoita kommentti…" className="flex-1 bg-black border border-primary/20 rounded px-3 py-2 text-sm"/><button className="rounded bg-primary text-primary-foreground px-3 py-2 text-xs">Lähetä</button></form></div>}</article>}
