/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeikkaaRouteImport } from './routes/veikkaa'
import { Route as UutisetRouteImport } from './routes/uutiset'
import { Route as TilastotRouteImport } from './routes/tilastot'
import { Route as TiimitRouteImport } from './routes/tiimit'
import { Route as TekoalytilaRouteImport } from './routes/tekoalytila'
import { Route as KuljettajatRouteImport } from './routes/kuljettajat'
import { Route as KilpailutRouteImport } from './routes/kilpailut'
import { Route as AsetuksetRouteImport } from './routes/asetukset'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UutisetIndexRouteImport } from './routes/uutiset.index'
import { Route as TilastotIndexRouteImport } from './routes/tilastot.index'
import { Route as TiimitIndexRouteImport } from './routes/tiimit.index'
import { Route as KuljettajatIndexRouteImport } from './routes/kuljettajat.index'
import { Route as KlubitIndexRouteImport } from './routes/klubit.index'
import { Route as KilpailutIndexRouteImport } from './routes/kilpailut.index'
import { Route as UutisetSlugRouteImport } from './routes/uutiset.$slug'
import { Route as TilastotKokoHistoriaRouteImport } from './routes/tilastot.koko-historia'
import { Route as TilastotSeasonRouteImport } from './routes/tilastot.$season'
import { Route as TiimitSlugRouteImport } from './routes/tiimit.$slug'
import { Route as KuljettajatSlugRouteImport } from './routes/kuljettajat.$slug'
import { Route as KilpailutSlugRouteImport } from './routes/kilpailut.$slug'

const VeikkaaRoute = VeikkaaRouteImport.update({
  id: '/veikkaa',
  path: '/veikkaa',
  getParentRoute: () => rootRouteImport,
} as any)
const UutisetRoute = UutisetRouteImport.update({
  id: '/uutiset',
  path: '/uutiset',
  getParentRoute: () => rootRouteImport,
} as any)
const TilastotRoute = TilastotRouteImport.update({
  id: '/tilastot',
  path: '/tilastot',
  getParentRoute: () => rootRouteImport,
} as any)
const TiimitRoute = TiimitRouteImport.update({
  id: '/tiimit',
  path: '/tiimit',
  getParentRoute: () => rootRouteImport,
} as any)
const TekoalytilaRoute = TekoalytilaRouteImport.update({
  id: '/tekoalytila',
  path: '/tekoalytila',
  getParentRoute: () => rootRouteImport,
} as any)
const KuljettajatRoute = KuljettajatRouteImport.update({
  id: '/kuljettajat',
  path: '/kuljettajat',
  getParentRoute: () => rootRouteImport,
} as any)
const KilpailutRoute = KilpailutRouteImport.update({
  id: '/kilpailut',
  path: '/kilpailut',
  getParentRoute: () => rootRouteImport,
} as any)
const AsetuksetRoute = AsetuksetRouteImport.update({
  id: '/asetukset',
  path: '/asetukset',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UutisetIndexRoute = UutisetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UutisetRoute,
} as any)
const TilastotIndexRoute = TilastotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TilastotRoute,
} as any)
const TiimitIndexRoute = TiimitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TiimitRoute,
} as any)
const KuljettajatIndexRoute = KuljettajatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KuljettajatRoute,
} as any)
const KlubitIndexRoute = KlubitIndexRouteImport.update({
  id: '/klubit/',
  path: '/klubit/',
  getParentRoute: () => rootRouteImport,
} as any)
const KilpailutIndexRoute = KilpailutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KilpailutRoute,
} as any)
const UutisetSlugRoute = UutisetSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UutisetRoute,
} as any)
const TilastotKokoHistoriaRoute = TilastotKokoHistoriaRouteImport.update({
  id: '/koko-historia',
  path: '/koko-historia',
  getParentRoute: () => TilastotRoute,
} as any)
const TilastotSeasonRoute = TilastotSeasonRouteImport.update({
  id: '/$season',
  path: '/$season',
  getParentRoute: () => TilastotRoute,
} as any)
const TiimitSlugRoute = TiimitSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TiimitRoute,
} as any)
const KuljettajatSlugRoute = KuljettajatSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KuljettajatRoute,
} as any)
const KilpailutSlugRoute = KilpailutSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KilpailutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asetukset': typeof AsetuksetRoute
  '/kilpailut': typeof KilpailutRouteWithChildren
  '/kuljettajat': typeof KuljettajatRouteWithChildren
  '/tekoalytila': typeof TekoalytilaRoute
  '/tiimit': typeof TiimitRouteWithChildren
  '/tilastot': typeof TilastotRouteWithChildren
  '/uutiset': typeof UutisetRouteWithChildren
  '/veikkaa': typeof VeikkaaRoute
  '/kilpailut/$slug': typeof KilpailutSlugRoute
  '/kuljettajat/$slug': typeof KuljettajatSlugRoute
  '/tiimit/$slug': typeof TiimitSlugRoute
  '/tilastot/$season': typeof TilastotSeasonRoute
  '/tilastot/koko-historia': typeof TilastotKokoHistoriaRoute
  '/uutiset/$slug': typeof UutisetSlugRoute
  '/kilpailut/': typeof KilpailutIndexRoute
  '/klubit/': typeof KlubitIndexRoute
  '/kuljettajat/': typeof KuljettajatIndexRoute
  '/tiimit/': typeof TiimitIndexRoute
  '/tilastot/': typeof TilastotIndexRoute
  '/uutiset/': typeof UutisetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asetukset': typeof AsetuksetRoute
  '/tekoalytila': typeof TekoalytilaRoute
  '/veikkaa': typeof VeikkaaRoute
  '/kilpailut/$slug': typeof KilpailutSlugRoute
  '/kuljettajat/$slug': typeof KuljettajatSlugRoute
  '/tiimit/$slug': typeof TiimitSlugRoute
  '/tilastot/$season': typeof TilastotSeasonRoute
  '/tilastot/koko-historia': typeof TilastotKokoHistoriaRoute
  '/uutiset/$slug': typeof UutisetSlugRoute
  '/kilpailut': typeof KilpailutIndexRoute
  '/klubit': typeof KlubitIndexRoute
  '/kuljettajat': typeof KuljettajatIndexRoute
  '/tiimit': typeof TiimitIndexRoute
  '/tilastot': typeof TilastotIndexRoute
  '/uutiset': typeof UutisetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asetukset': typeof AsetuksetRoute
  '/kilpailut': typeof KilpailutRouteWithChildren
  '/kuljettajat': typeof KuljettajatRouteWithChildren
  '/tekoalytila': typeof TekoalytilaRoute
  '/tiimit': typeof TiimitRouteWithChildren
  '/tilastot': typeof TilastotRouteWithChildren
  '/uutiset': typeof UutisetRouteWithChildren
  '/veikkaa': typeof VeikkaaRoute
  '/kilpailut/$slug': typeof KilpailutSlugRoute
  '/kuljettajat/$slug': typeof KuljettajatSlugRoute
  '/tiimit/$slug': typeof TiimitSlugRoute
  '/tilastot/$season': typeof TilastotSeasonRoute
  '/tilastot/koko-historia': typeof TilastotKokoHistoriaRoute
  '/uutiset/$slug': typeof UutisetSlugRoute
  '/kilpailut/': typeof KilpailutIndexRoute
  '/klubit/': typeof KlubitIndexRoute
  '/kuljettajat/': typeof KuljettajatIndexRoute
  '/tiimit/': typeof TiimitIndexRoute
  '/tilastot/': typeof TilastotIndexRoute
  '/uutiset/': typeof UutisetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asetukset'
    | '/kilpailut'
    | '/kuljettajat'
    | '/tekoalytila'
    | '/tiimit'
    | '/tilastot'
    | '/uutiset'
    | '/veikkaa'
    | '/kilpailut/$slug'
    | '/kuljettajat/$slug'
    | '/tiimit/$slug'
    | '/tilastot/$season'
    | '/tilastot/koko-historia'
    | '/uutiset/$slug'
    | '/kilpailut/'
    | '/klubit/'
    | '/kuljettajat/'
    | '/tiimit/'
    | '/tilastot/'
    | '/uutiset/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asetukset'
    | '/tekoalytila'
    | '/veikkaa'
    | '/kilpailut/$slug'
    | '/kuljettajat/$slug'
    | '/tiimit/$slug'
    | '/tilastot/$season'
    | '/tilastot/koko-historia'
    | '/uutiset/$slug'
    | '/kilpailut'
    | '/klubit'
    | '/kuljettajat'
    | '/tiimit'
    | '/tilastot'
    | '/uutiset'
  id:
    | '__root__'
    | '/'
    | '/asetukset'
    | '/kilpailut'
    | '/kuljettajat'
    | '/tekoalytila'
    | '/tiimit'
    | '/tilastot'
    | '/uutiset'
    | '/veikkaa'
    | '/kilpailut/$slug'
    | '/kuljettajat/$slug'
    | '/tiimit/$slug'
    | '/tilastot/$season'
    | '/tilastot/koko-historia'
    | '/uutiset/$slug'
    | '/kilpailut/'
    | '/klubit/'
    | '/kuljettajat/'
    | '/tiimit/'
    | '/tilastot/'
    | '/uutiset/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsetuksetRoute: typeof AsetuksetRoute
  KilpailutRoute: typeof KilpailutRouteWithChildren
  KuljettajatRoute: typeof KuljettajatRouteWithChildren
  TekoalytilaRoute: typeof TekoalytilaRoute
  TiimitRoute: typeof TiimitRouteWithChildren
  TilastotRoute: typeof TilastotRouteWithChildren
  UutisetRoute: typeof UutisetRouteWithChildren
  VeikkaaRoute: typeof VeikkaaRoute
  KlubitIndexRoute: typeof KlubitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veikkaa': {
      id: '/veikkaa'
      path: '/veikkaa'
      fullPath: '/veikkaa'
      preLoaderRoute: typeof VeikkaaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uutiset': {
      id: '/uutiset'
      path: '/uutiset'
      fullPath: '/uutiset'
      preLoaderRoute: typeof UutisetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tilastot': {
      id: '/tilastot'
      path: '/tilastot'
      fullPath: '/tilastot'
      preLoaderRoute: typeof TilastotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiimit': {
      id: '/tiimit'
      path: '/tiimit'
      fullPath: '/tiimit'
      preLoaderRoute: typeof TiimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tekoalytila': {
      id: '/tekoalytila'
      path: '/tekoalytila'
      fullPath: '/tekoalytila'
      preLoaderRoute: typeof TekoalytilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuljettajat': {
      id: '/kuljettajat'
      path: '/kuljettajat'
      fullPath: '/kuljettajat'
      preLoaderRoute: typeof KuljettajatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kilpailut': {
      id: '/kilpailut'
      path: '/kilpailut'
      fullPath: '/kilpailut'
      preLoaderRoute: typeof KilpailutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asetukset': {
      id: '/asetukset'
      path: '/asetukset'
      fullPath: '/asetukset'
      preLoaderRoute: typeof AsetuksetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uutiset/': {
      id: '/uutiset/'
      path: '/'
      fullPath: '/uutiset/'
      preLoaderRoute: typeof UutisetIndexRouteImport
      parentRoute: typeof UutisetRoute
    }
    '/tilastot/': {
      id: '/tilastot/'
      path: '/'
      fullPath: '/tilastot/'
      preLoaderRoute: typeof TilastotIndexRouteImport
      parentRoute: typeof TilastotRoute
    }
    '/tiimit/': {
      id: '/tiimit/'
      path: '/'
      fullPath: '/tiimit/'
      preLoaderRoute: typeof TiimitIndexRouteImport
      parentRoute: typeof TiimitRoute
    }
    '/kuljettajat/': {
      id: '/kuljettajat/'
      path: '/'
      fullPath: '/kuljettajat/'
      preLoaderRoute: typeof KuljettajatIndexRouteImport
      parentRoute: typeof KuljettajatRoute
    }
    '/klubit/': {
      id: '/klubit/'
      path: '/klubit'
      fullPath: '/klubit/'
      preLoaderRoute: typeof KlubitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kilpailut/': {
      id: '/kilpailut/'
      path: '/'
      fullPath: '/kilpailut/'
      preLoaderRoute: typeof KilpailutIndexRouteImport
      parentRoute: typeof KilpailutRoute
    }
    '/uutiset/$slug': {
      id: '/uutiset/$slug'
      path: '/$slug'
      fullPath: '/uutiset/$slug'
      preLoaderRoute: typeof UutisetSlugRouteImport
      parentRoute: typeof UutisetRoute
    }
    '/tilastot/koko-historia': {
      id: '/tilastot/koko-historia'
      path: '/koko-historia'
      fullPath: '/tilastot/koko-historia'
      preLoaderRoute: typeof TilastotKokoHistoriaRouteImport
      parentRoute: typeof TilastotRoute
    }
    '/tilastot/$season': {
      id: '/tilastot/$season'
      path: '/$season'
      fullPath: '/tilastot/$season'
      preLoaderRoute: typeof TilastotSeasonRouteImport
      parentRoute: typeof TilastotRoute
    }
    '/tiimit/$slug': {
      id: '/tiimit/$slug'
      path: '/$slug'
      fullPath: '/tiimit/$slug'
      preLoaderRoute: typeof TiimitSlugRouteImport
      parentRoute: typeof TiimitRoute
    }
    '/kuljettajat/$slug': {
      id: '/kuljettajat/$slug'
      path: '/$slug'
      fullPath: '/kuljettajat/$slug'
      preLoaderRoute: typeof KuljettajatSlugRouteImport
      parentRoute: typeof KuljettajatRoute
    }
    '/kilpailut/$slug': {
      id: '/kilpailut/$slug'
      path: '/$slug'
      fullPath: '/kilpailut/$slug'
      preLoaderRoute: typeof KilpailutSlugRouteImport
      parentRoute: typeof KilpailutRoute
    }
  }
}

interface KilpailutRouteChildren {
  KilpailutSlugRoute: typeof KilpailutSlugRoute
  KilpailutIndexRoute: typeof KilpailutIndexRoute
}

const KilpailutRouteChildren: KilpailutRouteChildren = {
  KilpailutSlugRoute: KilpailutSlugRoute,
  KilpailutIndexRoute: KilpailutIndexRoute,
}

const KilpailutRouteWithChildren = KilpailutRoute._addFileChildren(
  KilpailutRouteChildren,
)

interface KuljettajatRouteChildren {
  KuljettajatSlugRoute: typeof KuljettajatSlugRoute
  KuljettajatIndexRoute: typeof KuljettajatIndexRoute
}

const KuljettajatRouteChildren: KuljettajatRouteChildren = {
  KuljettajatSlugRoute: KuljettajatSlugRoute,
  KuljettajatIndexRoute: KuljettajatIndexRoute,
}

const KuljettajatRouteWithChildren = KuljettajatRoute._addFileChildren(
  KuljettajatRouteChildren,
)

interface TiimitRouteChildren {
  TiimitSlugRoute: typeof TiimitSlugRoute
  TiimitIndexRoute: typeof TiimitIndexRoute
}

const TiimitRouteChildren: TiimitRouteChildren = {
  TiimitSlugRoute: TiimitSlugRoute,
  TiimitIndexRoute: TiimitIndexRoute,
}

const TiimitRouteWithChildren =
  TiimitRoute._addFileChildren(TiimitRouteChildren)

interface TilastotRouteChildren {
  TilastotSeasonRoute: typeof TilastotSeasonRoute
  TilastotKokoHistoriaRoute: typeof TilastotKokoHistoriaRoute
  TilastotIndexRoute: typeof TilastotIndexRoute
}

const TilastotRouteChildren: TilastotRouteChildren = {
  TilastotSeasonRoute: TilastotSeasonRoute,
  TilastotKokoHistoriaRoute: TilastotKokoHistoriaRoute,
  TilastotIndexRoute: TilastotIndexRoute,
}

const TilastotRouteWithChildren = TilastotRoute._addFileChildren(
  TilastotRouteChildren,
)

interface UutisetRouteChildren {
  UutisetSlugRoute: typeof UutisetSlugRoute
  UutisetIndexRoute: typeof UutisetIndexRoute
}

const UutisetRouteChildren: UutisetRouteChildren = {
  UutisetSlugRoute: UutisetSlugRoute,
  UutisetIndexRoute: UutisetIndexRoute,
}

const UutisetRouteWithChildren =
  UutisetRoute._addFileChildren(UutisetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsetuksetRoute: AsetuksetRoute,
  KilpailutRoute: KilpailutRouteWithChildren,
  KuljettajatRoute: KuljettajatRouteWithChildren,
  TekoalytilaRoute: TekoalytilaRoute,
  TiimitRoute: TiimitRouteWithChildren,
  TilastotRoute: TilastotRouteWithChildren,
  UutisetRoute: UutisetRouteWithChildren,
  VeikkaaRoute: VeikkaaRoute,
  KlubitIndexRoute: KlubitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
